import { ProductProps } from "./store";

export const productsArr: ProductProps[] = [
  {
    id: 1,
    name: "Wireless Earbuds",
    description: "High-quality wireless earbuds with noise cancellation and 12-hour battery life.",
    price: 59.99,
    creation_date: new Date("2025-01-01"),
    url: "/src/assets/wireless_earbuds.jpg",
  },
  {
    id: 2,
    name: "Smart Fitness Tracker",
    description: "A lightweight fitness tracker that monitors heart rate, steps, and sleep patterns.",
    price: 89.99,
    creation_date: new Date("2024-12-15"),
    url: "/src/assets/smart_fitness_tracker.jpg",
  },
  {
    id: 3,
    name: "Ergonomic Office Chair",
    description: "Comfortable and adjustable office chair with lumbar support and breathable mesh fabric.",
    price: 199.99,
    creation_date: new Date("2024-11-30"),
    url: "/src/assets/ergonomic_office_chair.jpg",
  },
  {
    id: 4,
    name: "4K Action Camera",
    description: "Durable 4K action camera with waterproof casing and multiple shooting modes.",
    price: 129.99,
    creation_date: new Date("2024-10-22"),
    url: "/src/assets/4k_action_camera.jpg",
  },
  {
    id: 5,
    name: "Portable Bluetooth Speaker",
    description: "Compact Bluetooth speaker with powerful sound and up to 10 hours of playtime.",
    price: 39.99,
    creation_date: new Date("2024-09-15"),
    url: "/src/assets/portable_bt_speaker.jpg",
  },
  {
    id: 6,
    name: "Noise Cancelling Headphones",
    description: "Over-ear headphones with active noise cancellation and 30-hour battery life.",
    price: 129.99,
    creation_date: new Date("2025-01-06"),
    url: '/src/assets/noise_cancelling_hp.jpg',
  },
  {
    id: 7,
    name: "Portable Power Bank",
    description: "Compact power bank with 10,000mAh capacity for fast charging on the go.",
    price: 39.99,
    creation_date: new Date("2025-01-07"),
    url: '/src/assets/power_bank.jpg',
  },
  {
    id: 8,
    name: "Smart Light Bulb",
    description: "Energy-efficient smart bulb with adjustable brightness and color control via app.",
    price: 19.99,
    creation_date: new Date("2025-01-08"),
    url: '/src/assets/smart_light_bulb.jpg',
  },
  {
    id: 9,
    name: "Laptop Stand",
    description: "Adjustable ergonomic laptop stand for comfortable working posture.",
    price: 49.99,
    creation_date: new Date("2025-01-05"),
    url: '/src/assets/laptop_stand.jpg',
  },
  {
    id: 10,
    name: "Electric Toothbrush",
    description: "Rechargeable electric toothbrush with multiple cleaning modes and a 2-minute timer.",
    price: 39.99,
    creation_date: new Date("2025-01-10"),
    url: '/src/assets/electric_toothbrush.jpg',
  },
  {
    id: 11,
    name: "Wireless Mouse",
    description: "Ergonomic wireless mouse with adjustable DPI settings and long battery life.",
    price: 24.99,
    creation_date: new Date("2025-01-11"),
    url: '/src/assets/wireless_mouse.jpg',
  }
];